import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import katex from 'katex';
import { FORMULAS, KATEX_OPTIONS } from '../src/lib/formulas.ts';

/**
 * Renders the formulas once, at authoring time, into a committed module.
 *
 * The formulas never change while the page is open, so there is no reason to
 * ship a LaTeX parser to every visitor: KaTeX stays a development dependency
 * and only its output travels. LaTeX remains the source — `formulas.ts` is
 * still where a formula is written and read.
 *
 * Forgetting to re-run this after editing a formula is caught by
 * `formulas.test.ts`, which recompiles the list and compares.
 *
 *     npm run formulas
 */

const destination = fileURLToPath(new URL('../src/lib/formulas.mathml.ts', import.meta.url));

const entries = Object.entries(FORMULAS)
  .map(([key, tex]) => `  ${key}:\n    ${JSON.stringify(katex.renderToString(tex, KATEX_OPTIONS))},`)
  .join('\n');

writeFileSync(
  destination,
  `// Generated by \`npm run formulas\` from formulas.ts — do not edit by hand.
// The LaTeX stays the source; this is only its rendering, frozen so that KaTeX
// never has to be shipped to the browser.

export const MATHML: Record<string, string> = {
${entries}
};
`,
);

console.log(`${Object.keys(FORMULAS).length} formulas rendered into ${destination}`);
